<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['101', 'Oral Communication', 3, 'Core', 1, 1, 1],
            ['102', 'Komunikasyon at Pananaliksik sa Wika at Kulturang Pilipino', 3, 'Core', 1, 1, 1],
            ['103', 'General Mathematics', 3, 'Core', 1, 1, 1],
            ['104', 'Earth & Life Science', 3, 'Core', 1, 1, 1],
            ['105', 'Personal Development', 3, 'Core', 1, 1, 1],
            ['106', 'Physical Education 1', 1, 'Core', 1, 1, 1],
            ['107', 'Electrical Installation & Maintenance 111 (NCI)', 5, 'Applied and Specialized Subjects', 1, 1, 1],
            ['108', 'Reading and Writing', 3, 'Core', 1, 2, 1],
            ['109', '21st Century Literature from the Philippines and the world', 3, 'Core', 1, 2, 1],
            ['110', 'Physical Education and Health 2', 1, 'Core', 1, 2, 1],
            ['111', 'Practical Research 1', 3, 'Core', 1, 2, 1],
            ['112', 'Filipino sa Piling Larangan', 3, 'Applied and Specialized Subjects', 1, 2, 1],
            ['113', 'Empowerment Technologies', 3, 'Applied and Specialized Subjects', 1, 2, 1],
            ['114', 'Electrical Installation & Maintenance 112 (NCI)', 5, 'Applied and Specialized Subjects', 1, 2, 1],
            ['115', 'Pagbasa at Pagsuri ng iba\'t-ibang Teksto Tungo sa Pananaliksik', 3, 'Core', 1, 1, 2],
            ['116', 'Contemporary Philippine Arts from the Region', 3, 'Core', 1, 1, 2],
            ['117', 'Statistics and Probability', 3, 'Core', 1, 1, 2],
            ['118', 'Introduction to the Philiosophy of the Human Person', 3, 'Core', 1, 1, 1],
            ['119', 'Understanding Culture, Society & Politics', 3, 'Core', 1, 1, 2],
            ['120', 'Physical Education and Health 3', 1, 'Core', 1, 1, 2],
            ['121', 'Practical Research 2', 3, 'Applied and Specialized Subjects', 1, 1, 2],
            ['122', 'Electrical Installation & Maintenance 121 (NCI II)', 5, 'Applied and Specialized Subjects', 1, 1, 2],
            ['101', 'Oral Communication', 3, 'Core', 2, 1, 1],
            ['102', 'Komunikasyon at Pananaliksik sa Wika at Kulturang Pilipino', 3, 'Core', 2, 1, 1],
            ['103', 'General Mathematics', 3, 'Core', 2, 1, 1],
            ['104', 'Earth & Life Science', 3, 'Core', 2, 1, 1],
            ['105', 'Personal Development', 3, 'Core', 2, 1, 1],
            ['106', 'Physical Education 1', 3, 'Core', 2, 1, 1],
            ['107', 'Automotive Servicing 111 (NCI)', 5, 'Applied and Specialized Subjects', 2, 1, 1],
            ['123', 'Media & Information Literacy', 3, 'Core', 1, 2, 2],
            ['124', 'Physical Science', 3, 'Core', 1, 2, 2],
            ['125', 'Physical Education and Health 4', 1, 'Core', 1, 2, 1],
            ['126', 'English for Academic & Professional Purposes', 3, 'Applied and Specialized Subjects', 1, 2, 2],
            ['127', 'Entrepreneurship', 3, 'Applied and Specialized Subjects', 1, 2, 2],
            ['128', 'Injuries, Investigations & Immersion', 3, 'Applied and Specialized Subjects', 1, 2, 2],
            ['129', 'Electrical Installation & Maintenance 122 (NCI II)', 5, 'Applied and Specialized Subjects', 1, 2, 2],
            ['130', 'Work Immersion', 3, 'Applied and Specialized Subjects', 1, 2, 2],
            ['111', 'Reading and Writing', 3, 'Core', 2, 2, 1],
            ['112', '21st Century Literature from the Philippines and the world', 3, 'Core', 2, 2, 1],
            ['113', 'Physical Education and Health 2', 3, 'Core', 2, 2, 1],
            ['114', 'Practical Research 1', 3, 'Applied and Specialized Subjects', 2, 2, 1],
            ['115', 'Filipino sa Piling Larangan', 3, 'Applied and Specialized Subjects', 2, 2, 1],
            ['116', 'Empowerment Technologies', 3, 'Applied and Specialized Subjects', 2, 2, 1],
            ['117', 'Automotive Servicing 112 (NCI)', 5, 'Applied and Specialized Subjects', 2, 2, 1],
            ['118', 'Pagbasa at Pagsuri ng iba\'t-ibang Teksto Tungo sa Pananaliksik', 3, 'Core', 2, 1, 2],
            ['119', 'Contemporary Philippine Arts from the Region', 3, 'Core', 2, 1, 2],
            ['120', 'Statistics and Probability', 3, 'Core', 2, 1, 2],
            ['121', 'Introduction to the Philiosophy of the Human Person', 3, 'Core', 2, 1, 2],
            ['122', 'Understanding Culture, Society & Politics', 3, 'Core', 2, 1, 2],
            ['123', 'Physical Education and Health 3', 3, 'Core', 2, 1, 2],
            ['124', 'Practical Research 2', 3, 'Applied and Specialized Subjects', 2, 1, 2],
            ['125', 'Automotive Servicing 121 (NCI I)', 5, 'Applied and Specialized Subjects', 2, 1, 2],
            ['126', 'Media & Information Literacy', 3, 'Core', 2, 2, 2],
            [ '127', 'Physical Science', 3, 'Core', 2, 1, 2],
            [ '128', 'Physical Education and Health 4', 3, 'Core', 2, 2, 2],
            [ '129', 'English for Academic & Professional Purposes', 3, 'Applied and Specialized Subjects', 2, 2, 2],
            [ '130', 'Entrepreneurship', 3, 'Applied and Specialized Subjects', 2, 2, 2],
            [ '131', 'Inquiries, Investigations, & Immersion', 3, 'Applied and Specialized Subjects', 2, 2, 2],
            [ '132', 'Inquiries, Investigations, & Immersion', 3, 'Applied and Specialized Subjects', 2, 2, 2],
            [ '133', 'Automotive Servicing 122 (NCI II)', 5, 'Applied and Specialized Subjects', 2, 2, 2],
            [ '134', 'Work Immersion', 3, 'Applied and Specialized Subjects', 2, 2, 2],
            ['101', 'Oral Communication', 3, 'Core', 3, 1, 1],
            ['102', 'Komunikasyon at Pananaliksik sa Wika at Kulturang Pilipino', 3, 'Core', 3, 1, 1],
            ['103', 'General Mathematics', 3, 'Core', 3, 1, 1],
            ['104', 'Earth & Life Science', 3, 'Core', 3, 1, 1],
            ['105', 'Personal Development', 3, 'Core', 3, 1, 1],
            ['106', 'Physical Education 1', 3, 'Core', 3, 1, 1],
            ['107', 'Computer Systems Servicing 111 (NCI I)', 5, 'Applied and Specialized Subjects', 3, 1, 1],
            ['108', 'Reading and Writing', 3, 'Core', 3, 2, 1],
            ['109', '21st Century Literature from the Philippines and the world', 3, 'Core', 3, 1, 1],
            ['110', 'Physical Education and Health 2', 3, 'Core', 3, 2, 1],
            ['111', 'Practical Research 1', 3, 'Applied and Specialized Subjects', 3, 2, 1],
            ['112', 'Filipino sa Piling Larangan', 3, 'Applied and Specialized Subjects', 3, 2, 1],
            ['113', 'Empowerment Technologies', 3, 'Applied and Specialized Subjects', 3, 2, 1],
            ['114', 'Computer Hardware Servicing 112 (NCI II)', 5, 'Applied and Specialized Subjects', 3, 2, 1],
            ['115', 'Pagbasa at Pagsuri ng iba\'t-ibang Teksto Tungo sa Pananaliksik', 3, 'Core', 3, 1, 2],
            ['116', 'Contemporary Philippine Arts from the Region', 3, 'Core', 3, 1, 2],
            [ '117', 'Statistics and Probability', 3, 'Core', 3, 1, 2],
            [ '118', 'Introduction to the Philiosophy of the Human Person', 3, 'Core', 3, 1, 2],
            [ '119', 'Understanding Culture, Society & Politics', 3, 'Core', 3, 1, 2],
            [ '120', 'Physical Education and Health 3', 3, 'Core', 3, 1, 2],
            [ '121', 'Practical Research 2', 3, 'Applied and Specialized Subjects', 3, 1, 2],
            [ '122', 'Computer Hardware Servicing 121 (NCI III)', 5, 'Applied and Specialized Subjects', 3, 1, 2],
            [ '123', 'Media & Information Literacy', 3, 'Core', 3, 2, 2],
            [ '124', 'Physical Science', 3, 'Core', 3, 2, 2],
            [ '125', 'Physical Education and Health 4', 1, 'Core', 3, 2, 2],
            [ '126', 'English for Academic & Professional Purposes', 3, 'Applied and Specialized Subjects', 3, 2, 2],
            [ '127', 'Entrepreneurship', 3, 'Applied and Specialized Subjects', 3, 2, 2],
            [ '128', 'Inquiries, Investigations, & Immersion', 3, 'Applied and Specialized Subjects', 3, 2, 2],
            [ '129', 'Computer Hardware Servicing 122 (NCI II)', 3, 'Applied and Specialized Subjects', 3, 2, 2],
            [ '130', 'Work Immersion', 3, 'Applied and Specialized Subjects', 3, 2, 2],
            [ '101', 'Oral Communication', 3, 'Core', 4, 1, 1],
            [ '102', 'Komunikasyon at Pananaliksik sa Wika at Kulturang Pilipino', 3, 'Core', 4, 1, 1],
            [ '103', 'General Mathematics', 3, 'Core', 4, 1, 1],
            [ '104', 'Earth & Life Science', 3, 'Core', 4, 1, 1],
            [ '105', 'Personal Development', 3, 'Core', 4, 1, 1],
            [ '106', 'Physical Education 1', 3, 'Core', 4, 1, 1],
            [ '107', 'Housekeeping 111 (NCI)', 5, 'Applied and Specialized Subjects', 4, 1, 1],
            [ '108', 'Reading and Writing', 3, 'Core', 4, 2, 1],
            [ '109', '21st Century Literature from the Philippines and the world', 3, 'Core', 4, 2, 1],
            [ '110', 'Physical Education and Health 2', 3, 'Core', 4, 2, 1],
            [ '111', 'Practical Research 1', 3, 'Applied and Specialized Subjects', 4, 2, 1],
            [ '112', 'Filipino sa Piling Larangan', 3, 'Core', 4, 2, 1],
            [ '113', 'Empowerment Technologies', 3, 'Applied and Specialized Subjects', 4, 2, 1],
            [ '114', 'Front Office Services 112 (NCI II)', 3, 'Applied and Specialized Subjects', 4, 2, 1],
            [ '115', 'Pagbasa at Pagsuri ng iba\'t-ibang Teksto Tungo sa Pananaliksik', 3, 'Core', 4, 1, 2],
            [ '116', 'Contemporary Philippine Arts from the Region', 3, 'Core', 4, 1, 2],
            [ '118', 'Statistics and Probability', 3, 'Core', 4, 1, 2],
            [ '118', 'Introduction to the Philiosophy of the Human Person', 3, 'Core', 4, 1, 2],
            [ '119', 'Understanding Culture, Society & Politics', 3, 'Core', 4, 1, 2],
            ['120', 'Physical Education and Health 3', 3, 'Core', 4, 1, 2],
            [ '121', 'Practical Research 2', 3, 'Applied and Specialized Subjects', 4, 1, 2],
            [ '122', 'Food and Beverage Services (NCI III)', 5, 'Applied and Specialized Subjects', 4, 1, 2],
            [ '123', 'Media & Information Literacy', 3, 'Core', 4, 2, 2],
            [ '124', 'Physical Science', 3, 'Core', 4, 2, 2],
            [ '125', 'Physical Education and Health 4', 3, 'Core', 4, 2, 2],
            [ '126', 'English for Academic & Professional Purposes', 3, 'Applied and Specialized Subjects', 4, 2, 2],
            [ '127', 'Entrepreneurship', 3, 'Applied and Specialized Subjects', 4, 2, 2],
            [ '128', 'Inquiries, Investigations, & Immersion', 3, 'Applied and Specialized Subjects', 4, 2, 2],
            ['129', 'Bread and Pastry Production 122 (NCI III)', 5, 'Applied and Specialized Subjects', 4, 2, 2],
            [ '130', 'Work Immersion', 3, 'Applied and Specialized Subjects', 4, 2, 2]
        ];
        foreach ($data as $key => $value) {
            \App\Models\Subject::create([
                'code' => $value[0],
                'name' => $value[1],
                'unit' => $value[2],
                'type' => $value[3],
                'specialization_id' => $value[4],
                'semester_id' => $value[5],
                'grade_level_id' => $value[6],
            ]);
        }
    }
}
